language: java

jdk:
  - oraclejdk8

services:
  - docker



install:
  - mvn install -DskipTests=true -B -V -Psign -Dgpg.passphrase=$GPG_PASSPHRASE
  - docker build -t $TRAVIS_REPO_SLUG .

script:
  - mvn test -B


cache:
  directories:
  - $HOME/.m2